### ISSUE TITLE
How many epochs are there in this article

### ISSUE THREAD

**Issue by liufangcen** [agonzgarc/cross-domain-disen#2]
@agonzgarc  Awsome work! I am very inspaired by your work! 
And may I ask how many epochs this code needs to run? I found that the code could not stop, and I can not find where to define the epochs. Forgive that I am a new learner about tensorflow...

and Whether there is code for retrieve?

**Comment by agonzgarc** [comment]
Hi @liufangcen, thanks for your interest.

The number of epochs depends on the complexity and size of the dataset. For example, for MNIST-CD/CB I only ran it for 15 epochs, whereas more complex datasets need many more (e.g. 900 for 3D cars). You can see exactly how many epochs I used for each dataset in the appendix of the [paper](https://arxiv.org/pdf/1805.09730.pdf).

You can set the number of epochs by using the input flag _--max_epochs_. If unset, it trains for  2^32 steps.

**Comment by liufangcen** [comment]
thank you very much.
and where is the retrieval module in your code?
